### ISSUE TITLE
如果要做图片上添加标题怎么做啊。

### ISSUE THREAD

**Issue by wang521314** [crazyandcoder/ImageZoom#3]
我看了您的demo里面把展示的操作自己在另一个界面自己完成了，但是现在我在展示图片时同样也要展示出图片名，这样改怎么做。

**Comment by crazyandcoder** [comment]
传入图片地址和相应的title，修改布局文件，添加title显示的View，在(该文件类中修改即可)[https://github.com/crazyandcoder/ImageZoom/blob/master/imagezoom/src/main/java/com/liji/imagezoom/activity/ImageDetailFragment.java]

**Comment by wang521314** [comment]
谢谢
